### ISSUE TITLE
Cannot compile Ammonia with html5ever 0.22.8 as that dependency has been yanked

### ISSUE THREAD

**Issue by Figments** [rust-ammonia/ammonia#115]
As it says in the title, Ammonia refuses to compile as Cargo cannot find html5ever 0.22.8. Upon investigation, it seems that version was yanked from crates.io. It looks like Ammonia will need to update to version 0.23.0.

**Comment by lnicola** [comment]
That was done in #114, but a new release wasn't tagged.

**Comment by Figments** [comment]
Ah, awesome. Will a new release be pushed out soon?

**Comment by lnicola** [comment]
Hopefully, see #116.

**Comment by lnicola** [comment]
@notriddle I tagged a new release. Can you upload it to `crates.io`?

**Comment by notriddle** [comment]
It's released.

**Comment by Figments** [comment]
Sweet, thanks!
