### ISSUE TITLE
Consider adding pattern-matching for attribute filtering

### ISSUE THREAD

**Issue by shekyan** [rust-ammonia/ammonia#126]
Data attributes is a common pattern in modern web apps
`<div data-foo="42" />`

and sometimes it's ok to preserve them. Consider adding a pattern-matching based API to whitelist by a prefix.

**Comment by dingelish** [comment]
Anyone on this? I can provide a patch for whitelist supporting. Wonder if it can get these changes feature gated and merged to the upstream.

**Comment by dingelish** [comment]
more specifically, since prefix `data-` is widely adopted as "Data attributes", can we simply provide an API to allow the `data-` prefix?

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by dingelish** [comment]
seems we can close this by #131 :-)
