### ISSUE TITLE
Reporting security issue

### ISSUE THREAD

**Issue by securityMB** [rust-ammonia/ammonia#140]
Hey,

I'd like to report a security issue (bypass of ammonia in non-standard configuration). However I cannot find any information how to do so. Can you give some email address or other information where to report such bugs?

**Comment by lnicola** [comment]
@notriddle ^

**Comment by notriddle** [comment]
You can send it to my personal email, on my GitHub profile page.

**Comment by securityMB** [comment]
Thanks! I've just sent you an email.
