### ISSUE TITLE
Hook to sanitize `style` contents

### ISSUE THREAD

**Issue by xmo-odoo** [rust-ammonia/ammonia#179]
I don't know whether Ammonia would want to bundle [a CSS sanitizer](https://bleach.readthedocs.io/en/latest/clean.html#sanitizing-css), but the ability to handle that somewhat finely without needing to resort to a full-blown [`attribute_filter`](https://docs.rs/ammonia/latest/ammonia/struct.Builder.html#method.attribute_filter) would be nice.

**Comment by merlinz01** [comment]
This would be a great plus for Python users moving from the now-deprecated [bleach](https://github.com/mozilla/bleach), and it would allow for better integration with things like CKEditor.

**Comment by merlinz01** [comment]
Unfortunately although I would love to see a style sanitizer, I don't really have the time to implement it at this point, so I'm just being content with fewer features of CKEditor for now.

A quick search on crates.io turns up `parcel_css`, `lightningcss`, `css-minify`, `css-parser-rs` for other CSS parsers. I didn't check if any of them claim to support full CSS syntax. Although for an application like CKEditor's output, you won't be needing to parse `calc()` expressions or `@import` declarations, etc; it's styles are fairly basic from what I've seen.

I suppose an implementation would involve parsing the CSS with a spec-compliant parser, running over the AST with a user-defined whitelist, and outputting the CSS again into the HTML element's style attribute.
