### ISSUE TITLE
How to avoid replacing special characters like `&` ?

### ISSUE THREAD

**Issue by Nutomic** [rust-ammonia/ammonia#184]
The `clean` function in ammonia 3.3 unexpectedly replaces HTML special characters like `&` with `&amp;`, same for `<`, `>` and so on. Based on the docs and code, this should only happen with the `clean_text` function which Im not invoking at all. In fact I cant tell where these character replacements are happening or how to disable them. Any hints?

Edit: To reproduce, the following assertion fails but I would expect it to pass:
```rust
let sanitized = ammonia::clean("&!<>?");
assert_eq!(sanitized, "&!<>?");
```

**Comment by Nutomic** [comment]
That would only work if ammonia respects `<pre>` tags and doesnt change anything inside them. Is that the case?

**Comment by Nutomic** [comment]
That might be true in HTML, but when you write a markdown code block like the following, you expect it to be rendered unchanged, which Github indeed does.
```
<script>alert("xss example");</script>
```

Or 
``` 
docker-compose pull && docker-compose up -d
```

We also have a different, but related problem because we need to escape the same string twice in some cases. This is necessary because each time it is untrusted in a different context. Which results in `&` turning to `&amp;amp;`. 

All in all its really complicated to find a proper solution.

**Comment by lnicola** [comment]
Can you wrap the code blocks in `<![CDATA[]]>`?

**Comment by Nutomic** [comment]
Im closing this issue because ammonia isnt the right tool for our use case. Instead we are going to manually replace special html characters with escape codes.
