### ISSUE TITLE
HTML detector function

### ISSUE THREAD

**Issue by notriddle** [rust-ammonia/ammonia#75]
As nice as it is to be able to remove the blatantly bad stuff, sometimes you don't want the user to be able to enter any HTML at all. You could do this by escaping the markup, but if having a database with `&lt;` in it doesn't appeal to you, or you're worried about double-escaping or similarly nasty accidents, you could use a function that just tells you if a string has any HTML tags in it. And in case you wonder why anybody would want a library for that, it's not actually that easy to detect HTML without any false positives or false negatives.

We should be able to do this pretty easily:

* Parse the string as an HTML snippet
* Return true if the resulting HTML fragment contains exactly one node, and that node is of type TEXT

**Comment by lnicola** [comment]
Another similar use case might be "strip HTML and keep only the text", e.g. go from `This is <span>some</span> text` to `This is some text`, though I'm not sure how that should work for all elements.

**Comment by notriddle** [comment]
Just use the regular mode and set the `allowed_elements` to the empty set.

**Comment by lnicola** [comment]
Right, that works. I thought that would remove the text in those element, but it looks like it's kept.

**Comment by stanciuadrian** [comment]
It seems that `html5ever` gives the same tree structure for `s` and `<html>s</html>`:
```
 NodeData::Document
 +-+ NodeData::Element with name:html
   +-- NodeData::Text with contents:s
```

**Comment by notriddle** [comment]
You need to parse it as a document fragment instead of as the whole document. That'll prevent html5ever from inferring the document structure.

**Comment by lnicola** [comment]
@notriddle That happens even with `parse_fragment` as used in `make_parser`.

**Comment by notriddle** [comment]
That's annoying. It's supposed to be parsing the fragment as if it was inside a `<div>` tag.

**Comment by lnicola** [comment]
I opened https://github.com/servo/html5ever/issues/323 about this.

**Comment by notriddle** [comment]
We should probably use https://play.rust-lang.org/?gist=dd917d5f859ac115971d8355e5ab3dd2&version=stable instead, then.

**Comment by Ygg01** [comment]
Just a small warning. The code I whipped out is pretty basic, feel free to change it around. E.g. remove `println`.
